<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Discovery\MIN.Discovery.DI\MIN.Discovery.DI.csproj" />
    <ProjectReference Include="..\..\FileTransfer\MIN.FileTransfer.DI\MIN.FileTransfer.DI.csproj" />
    <ProjectReference Include="..\..\Sessions\Core\MIN.Sessions.Core.DI\MIN.Sessions.Core.DI.csproj" />
  </ItemGroup>

</Project>
