<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <ApplicationIcon>logo.ico</ApplicationIcon>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
    <Folder Include="ViewModels\Modals\" />
    <Folder Include="Views\Modals\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="Avalonia.Themes.Simple" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Svg.Controls.Skia.Avalonia" />
    <PackageReference Include="Xaml.Behaviors.Interactivity" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\DI\MIN.DI\MIN.DI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\Pages\DiscoveryPage.axaml.cs">
      <DependentUpon>DiscoveryPage.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Pages\SettingsSideBarPage.axaml.cs">
      <DependentUpon>SettingsSideBarPage.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Windows\MainWindow.axaml.cs">
      <DependentUpon>MainWindow.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
